#ifndef FRAMEWORK_MESSAGE_TYPES_H
#define FRAMEWORK_MESSAGE_TYPES_H

#define MESSAGE_SIZE 17

#define COMMAND 0
#define ACTOR_TYPE 1
#define ACTOR_ID 2
#define ACTOR_ID_DEST 3
#define WORKERS_NUM 4
#define WORKER_PID 5
#define INIT_ACTORS_NUM 6
#define MAX_ACTORS_NUM 7

#endif
