#ifndef SIMULATION_COMMANDS_H
#define SIMULATION_COMMANDS_H

	#define TIMESTEP_START 30
	#define TIMESTEP_END 31

	#define SPAWN_SQUIRREL_COMMAND 32
	#define KILL_SQUIRREL_COMMAND 33
	#define INFECTED_SQUIRREL_COMMAND 34

#endif
