#ifndef COMMANDS_H
#define COMMANDS_H

	#define SPAWN_ACTOR_COMMAND 0
	#define KILL_ACTOR_COMMAND 1
	#define DISCOVER_ACTOR_COMMAND 2
	#define FORGET_ACTOR_COMMAND 3

	#define KILL_WORKER_COMMAND 10
	#define START_WORKER_COMMAND 11

	#define VISIT_ACTOR_COMMAND 20
	#define PING_ACTOR_COMMAND 21

	#define TIMESTEP_START 30
	#define TIMESTEP_END 31
	#define TIMESTEP_END_GAVE_BIRTH 32


#endif
