Actor framework: simulation/cell.cpp File Reference
cell.cpp File Reference
#include "cell.h"
Functions
static void parse_message_simulate (Actor *actor, Message message)
parses the types of messages for this cell and do the appropriate actions
Function Documentation
static void parse_message_simulate (Actor * actor, Message message) static
parses the types of messages for this cell and do the appropriate actions
Parameters
actor Pointer to this Actor
message Input message
References ACTOR_ID, CLOCK_ID, COMMAND, Message::get(), INFECTION_LEVEL, Cell::infection_level, Cell::month, POPULATION_INFLUX, Cell::population_influx, Actor::send_msg(), Message::set(), TIMESTEP_END, VISIT_CELL_COMMAND, and Cell::visited().
{
     Cell *cell = dynamic_cast<Cell*>(actor);
     int actor_id;
     if(message.get(COMMAND) == VISIT_CELL_COMMAND) {
         actor_id = message.get(ACTOR_ID);
         cell->visited(message);
     }
     else if(message.get(COMMAND) == TIMESTEP_END) {
         actor_id = CLOCK_ID;
         cell->month++;
         cell->population_influx[cell->month%3] = 0;
         cell->infection_level[cell->month%2] = 0;
     }
     else
         assert(0);
     // sum the population_influx and infection level
     int curr_population_influx = accumulate(cell->population_influx.begin(), cell->population_influx.end(), 0);
     int curr_infection_level = accumulate(cell->infection_level.begin(), cell->infection_level.end(), 0);
     message.set(POPULATION_INFLUX, curr_population_influx);
     message.set(INFECTION_LEVEL, curr_infection_level);
     cell->send_msg(actor_id, message);
 }