Actor framework: Squirrel Class Reference
Squirrel Class Reference
Derived class of Actor.
#include <squirrel.h>
Public Member Functions
Squirrel (int id, int workers_num, float x, float y, int healthy)
Squirrel constructor.
~Squirrel ()
Squirrel destructor.
void move ()
If a squirrel steps and ends up in the same cell, this counts as a squirrel arriving in the cell. Squirrels that are born in a cell do not contribute to the populationInflux at the instant that they are born.
void birth ()
After every 50 steps, a squirrel will reproduce with a probability depending only on the average populationInflux of all of the cells they have visited in their last 50 steps.
void catch_disease ()
After every step, the squirrel will catch the disease with a probability depending on the infectionLevel of all the cells they have visited in the last 50 steps.
void die ()
An infected squirrel will live for a minimum of 50 steps, after this then they will die with a fixed probability of 1/6 for each step after.
bool should_act ()
Decide if the squirrel should act.
Public Member Functions inherited from Actor
Actor (int id, int type, int workers_num)
Actor constructor.
virtual ~Actor ()=0
Actor destructor.
int get_id ()
void set_state (int state)
Sets new FSM state to the Actor.
void compute ()
Executes the compute function of the Actor based on its current state.
void process (Message message)
Executes the parse message function of the Actor based on its current state.
void send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
void kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
Actor (int id, int type, int workers_num)
Actor constructor.
virtual ~Actor ()=0
Actor destructor.
int get_id ()
void set_state (int state)
Sets new FSM state to the Actor.
void compute ()
Executes the compute function of the Actor based on its current state.
void process (Message message)
Executes the parse message function of the Actor based on its current state.
void send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
void kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
Public Attributes
long seed
unique negative number for each squirrel actor
float x
float number taking values from 0.0 to 0.999 describing the x position in the landscape
float y
float number taking values from 0.0 to 0.999 describing the y position in the landscape
int healthy
float number taking values 1 or 0 describing if a squirrel is healthy or not if it is set to 0 it cannot change to 1
int step_no
Squirrels steps number.
int infected_steps
Squirrels infected steps.
vector< int > population_influx
Vector containing the population influx of the last 50 visited Cells.
vector< int > infection_level
Vector containing the infection level of the last 50 visited Cells.
milliseconds begin_time
Time in milliseconds that the previous step was.
Additional Inherited Members
Protected Member Functions inherited from Actor
void register_state (int state, void(compute_f)(Actor *))
Adds the given compute function to the compute_map based on the given state in FSM.
void register_state (int state, void(parse_message_f)(Actor *, Message))
Adds the given parse message function to the compute_map based on the given state in FSM.
void create_actor (Message message)
Sends message to the master to create a new Actor.
void kill_actor ()
Sends message to the master and the appropriate worker(this worker) to kill this actor.
void register_state (int state, void(compute_f)(Actor *))
Adds the given compute function to the compute_map based on the given state in FSM.
void register_state (int state, void(parse_message_f)(Actor *, Message))
Adds the given parse message function to the compute_map based on the given state in FSM.
void create_actor (Message message)
Sends message to the master to create a new Actor.
void kill_actor ()
Sends message to the master and the appropriate worker(this worker) to kill this actor.
Detailed Description
Derived class of Actor.
class Squirrel is an Actor holding vital information for this entity and providing functionality
Constructor & Destructor Documentation
Squirrel::Squirrel (int id, int workers_num, float x, float y, int healthy)
Squirrel constructor.
Parameters
id id of the squirrel
workers_num number of active workers it should be passed in the parent class
x initial position x of squirrel
y initial position y of squirrel
healthy initial health status of squirrel
References begin_time, compute_live(), Actor::get_id(), healthy, infected_steps, infection_level, initialiseRNG(), INTERACT, LIVE, parse_message_interact(), population_influx, Actor::register_state(), seed, Actor::set_state(), step_no, STEPS_MEMORY, x, and y.
                                                                         : Actor(id, ACTOR_TYPE_SQUIRREL, workers_num) {
     assert((healthy == 0 || healthy == 1) && x>=0.0 && x<0.999 && y>=0.0 && y<0.999);
     this->x = x;
     this->y = y;
     this->healthy = healthy;
     this->step_no = 0;
     this->infected_steps = 0;
     this->population_influx = vector<int>(STEPS_MEMORY);
     this->infection_level = vector<int>(STEPS_MEMORY);
     this->seed = -this->get_id() - 1;
     this->begin_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
     // called once for each actor
     initialiseRNG(&this->seed);
     for (int i = 0; i < STEPS_MEMORY; ++i) {
         this->population_influx[i] = 0;
         this->infection_level[i] = 0;
     }
     this->set_state(LIVE);
     this->register_state(LIVE, compute_live);
     this->register_state(INTERACT, parse_message_interact);
 }
Squirrel::~Squirrel ()
Squirrel destructor.
 {}
Member Function Documentation
void Squirrel::birth ()
After every 50 steps, a squirrel will reproduce with a probability depending only on the average populationInflux of all of the cells they have visited in their last 50 steps.
References CLOCK_ID, COMMAND, Actor::create_actor(), HEALTHY, population_influx, seed, Actor::send_msg(), Message::set(), SPAWN_SQUIRREL_COMMAND, step_no, STEPS_MEMORY, willGiveBirth(), X, x, Y, and y.
                      {
     if(this->step_no%STEPS_MEMORY == 0) {
         float avg_pop = 0;
         for (int i = 0; i < STEPS_MEMORY; ++i)
             avg_pop += this->population_influx[i];
         avg_pop /= STEPS_MEMORY;
         if(willGiveBirth(avg_pop, &this->seed)) {
             Message message;
             message.set(COMMAND, SPAWN_SQUIRREL_COMMAND);
             this->send_msg(CLOCK_ID, message);
             // new squirrels are born healthy
             message.set(HEALTHY, 1);
             // new squirrels are born in the same position as their parents
             message.set(X, this->x);
             message.set(Y, this->y);
             this->create_actor(message);
         }
     }
 }
void Squirrel::catch_disease ()
After every step, the squirrel will catch the disease with a probability depending on the infectionLevel of all the cells they have visited in the last 50 steps.
References CLOCK_ID, COMMAND, healthy, INFECTED_SQUIRREL_COMMAND, infection_level, seed, Actor::send_msg(), Message::set(), STEPS_MEMORY, and willCatchDisease().
{
     float avg_inf_level = 0;
     if(this->healthy == 0)
         return;
     for (int i = 0; i < STEPS_MEMORY; ++i)
         avg_inf_level += this->infection_level[i];
     avg_inf_level /= STEPS_MEMORY;
     this->healthy = !willCatchDisease(avg_inf_level, &this->seed);
     if(this->healthy == 0) {
         Message message;
         message.set(COMMAND, INFECTED_SQUIRREL_COMMAND);
         this->send_msg(CLOCK_ID, message);
     }
 }
void Squirrel::die ()
An infected squirrel will live for a minimum of 50 steps, after this then they will die with a fixed probability of 1/6 for each step after.
References CLOCK_ID, COMMAND, DIED, healthy, infected_steps, Actor::kill_actor(), KILL_SQUIRREL_COMMAND, seed, Actor::send_msg(), Message::set(), Actor::set_state(), STEPS_MEMORY, and willDie().
                    {
     if(this->infected_steps >= STEPS_MEMORY && willDie(&this->seed)) {
         assert(this->healthy == 0);
         this->set_state(DIED);
         Message message;
         message.set(COMMAND, KILL_SQUIRREL_COMMAND);
         this->send_msg(CLOCK_ID, message);
         this->kill_actor();
     }
 }
void Squirrel::move ()
If a squirrel steps and ends up in the same cell, this counts as a squirrel arriving in the cell. Squirrels that are born in a cell do not contribute to the populationInflux at the instant that they are born.
References catch_disease(), COMMAND, getCellFromPosition(), HEALTHY, healthy, INTERACT, seed, Actor::send_msg(), Message::set(), Actor::set_state(), squirrelStep(), VISIT_CELL_COMMAND, x, and y.
                     {
     this->set_state(INTERACT);
     squirrelStep(this->x, this->y, &this->x, &this->y, &this->seed);
     int cell_num = getCellFromPosition(this->x, this->y);
     assert(cell_num >=0 && cell_num <16);
     Message message;
     message.set(COMMAND, VISIT_CELL_COMMAND);
     message.set(HEALTHY, this->healthy);
     this->send_msg(cell_num, message);
     this->catch_disease();
 }
bool Squirrel::should_act ()
Decide if the squirrel should act.
References seed, and willAct().
{
     return willAct(&this->seed);
 }
Member Data Documentation
milliseconds Squirrel::begin_time
Time in milliseconds that the previous step was.
int Squirrel::healthy
float number taking values 1 or 0 describing if a squirrel is healthy or not if it is set to 0 it cannot change to 1
int Squirrel::infected_steps
Squirrels infected steps.
vector<int> Squirrel::infection_level
Vector containing the infection level of the last 50 visited Cells.
vector<int> Squirrel::population_influx
Vector containing the population influx of the last 50 visited Cells.
long Squirrel::seed
unique negative number for each squirrel actor
int Squirrel::step_no
Squirrels steps number.
float Squirrel::x
float number taking values from 0.0 to 0.999 describing the x position in the landscape
float Squirrel::y
float number taking values from 0.0 to 0.999 describing the y position in the landscape
The documentation for this class was generated from the following files:
simulation/squirrel.h
simulation/squirrel.cpp