Actor framework: Actor_framework Class Reference
Actor_framework Class Reference
Primary interface of actor framework.
#include <actor_framework_interface.h>
Static Public Member Functions
static void register_init_actors (void(init_actors)(Message message))
registers the initialisation actors callback
static void register_spawn_actor (Actor *(spawn_actor)(Message message))
registers the initialisation actors callback
static void spawn_actor (Message message)
calls the spawn actor callback function in the Master process
static void actor_framework (Message message)
initialises the MPI process setting up the environment
static void register_init_actors (void(init_actors)(Message message))
registers the initialisation actors callback
static void register_spawn_actor (Actor *(spawn_actor)(Message message))
registers the initialisation actors callback
static void spawn_actor (Message message)
calls the spawn actor callback function in the Master process
static void actor_framework (Message message)
initialises the MPI process setting up the environment
Static Private Member Functions
static void worker_code (int pid)
create a new worker object and executes its run function
static void master_code (Message message)
executes the run function of master process
Static Private Attributes
static void(* init_actors)(Message message)
pointer to a provided callback function that initialises the actors in the simulation based on the data in the given message
Detailed Description
Primary interface of actor framework.
A class that provides a set of functions for the simulation to initialise the framework
Member Function Documentation
static void Actor_framework::actor_framework (Message message) static
initialises the MPI process setting up the environment
Parameters
message data containing the input arguments of the process
void Actor_framework::actor_framework (Message message) static
initialises the MPI process setting up the environment
Parameters
message data containing the input arguments of the process
References Messenger::init_types(), master_code(), MASTER_PID, UPPER_BOUND_BUFFER_SIZE, and worker_code().
{
     int pid, world_size;
     int bsize;
     char *buffer, *bbuffer;
     MPI_Init(NULL, NULL);
     Messenger::init_types();
     MPI_Comm_rank(MPI_COMM_WORLD, &pid);
     MPI_Comm_size(MPI_COMM_WORLD, &world_size);
     if(world_size < 2) {
         cerr << "The simulation must run on more that 1 process\n";
     }
     else {
         MPI_Pack_size( UPPER_BOUND_BUFFER_SIZE, MPI_BYTE, MPI_COMM_WORLD, &bsize );
         buffer = (char *) malloc( bsize );
         MPI_Buffer_attach( buffer, bsize );
         if (pid == MASTER_PID)
             Actor_framework::master_code(message);
         else
             Actor_framework::worker_code(pid);
         MPI_Buffer_detach( &bbuffer, &bsize );
     }
     MPI_Finalize();
 }
void Actor_framework::master_code (Message message) static private
executes the run function of master process
Parameters
message a message containing vital infromation
References Master::finalize(), init_actors, Master::run(), Message::set(), Master::set_workers_num(), and WORKERS_NUM.
{
     int world_size, workers_num;
     MPI_Comm_size(MPI_COMM_WORLD, &world_size);
     workers_num = world_size - 1;
     Master::set_workers_num(workers_num);
     vector<int> workers_pid;
     for (int i = 1; i < world_size; ++i) {
         workers_pid.push_back(i);
         cout << "Worker started on MPI process " << i << endl;
     }
     message.set(WORKERS_NUM, workers_num);
     Actor_framework::init_actors(message);
     Master::run();
     Master::finalize();
 }
static void Actor_framework::register_init_actors (void(init_actors)(Message message)) static
registers the initialisation actors callback
Parameters
init_actors pointer to a provided callback function that initialises the actors in the simulation based on the data in the given message
void Actor_framework::register_init_actors (void(init_actors)(Message message)) static
registers the initialisation actors callback
Parameters
init_actors pointer to a provided callback function that initialises the actors in the simulation based on the data in the given message
References init_actors.
{
     Actor_framework::init_actors = init_actors;
 }
static void Actor_framework::register_spawn_actor (Actor * spawn_actor)(Message message) static
registers the initialisation actors callback
Parameters
spawn_actor pointer to a provided callback function that Master process uses to spawn new actors
void Actor_framework::register_spawn_actor (Actor * spawn_actor)(Message message) static
registers the initialisation actors callback
Parameters
spawn_actor pointer to a provided callback function that Master process uses to spawn new actors
References Worker::register_spawn_actor(), and spawn_actor().
{
     Worker::register_spawn_actor(spawn_actor);
 }
static void Actor_framework::spawn_actor (Message message) static
calls the spawn actor callback function in the Master process
Parameters
message data for the creation of the new actor
void Actor_framework::spawn_actor (Message message) static
calls the spawn actor callback function in the Master process
Parameters
message data for the creation of the new actor
References Master::spawn_actor().
{
     Master::spawn_actor(message);
 }
void Actor_framework::worker_code (int pid) static private
create a new worker object and executes its run function
Parameters
pid worker process pid
References Worker::finalize(), and Worker::run().
{
     Worker *worker = new Worker(pid);
     worker->run();
     worker->finalize();
     delete worker;
 }
Member Data Documentation
void(* Actor_framework::init_actors)(Message message) static private
pointer to a provided callback function that initialises the actors in the simulation based on the data in the given message
The documentation for this class was generated from the following files:
simulation/actor_framework_interface.h
actor_framework/actor_framework.h
actor_framework/actor_framework.cpp