Actor framework: Worker Class Reference
Worker Class Reference
#include <worker.h>
Public Member Functions
Worker (int pid)
Worker constructor.
~Worker ()
Worker destructor.
void run ()
main functionality of worker
void finalize ()
finalize method of worker
Static Public Member Functions
static void register_spawn_actor (Actor *(spawn_actor)(Message message))
registers the spawn actor function
Private Member Functions
void add_actor (Actor *actor)
add a new actor
void remove_actor (int actor_id)
removes the requested actor
Actor * find_actor (int actor_id)
finds the requested actor
void kill_all_actors ()
kill all the actors in the worker
void compute ()
Executes the compute function of the worker.
int process (Message message)
Executes the parse message function of the worker.
Private Attributes
int pid
worker process number
vector< Actor * > actors
vector that contains pointers to the actors that live in this worker
bool start_simulation
indicates if the simulation should start or not
int actors_spawned
number of spawned actors in this worker
int actors_died
number of died actors in this worker
Static Private Attributes
static Actor *(* spawn_actor)(Message message)
function pointer to the given callback that spawns actors
Detailed Description
class containing information and functionality for the Worker process
Constructor & Destructor Documentation
Worker::Worker (int pid)
Worker constructor.
Parameters
pid process id of worker
References actors, actors_died, actors_spawned, pid, and start_simulation.
                       {
     this->pid = pid;
     this->actors = vector<Actor*>();
     this->start_simulation = false;
     this->actors_spawned = 0;
     this->actors_died = 0;
 }
Worker::~Worker ()
Worker destructor.
References actors.
                 {
     for(auto actor : this->actors)
         delete actor;
 }
Member Function Documentation
void Worker::add_actor (Actor * actor) private
add a new actor
Parameters
pointer to the new actor structure
References actors, and actors_spawned.
{
     assert(actor != nullptr);
     this->actors_spawned++;
     this->actors.push_back(actor);
 }
void Worker::compute () private
Executes the compute function of the worker.
References actors, and start_simulation.
                      {
     if(this->start_simulation == false)
         return;
     for (auto actor : this->actors) {
         actor->compute();
     }
 }
void Worker::finalize ()
finalize method of worker
References actors_died, actors_spawned, and pid.
                       {
     cout << "Worker " << this->pid << " finalized: actors_spawned = " << this->actors_spawned << ", actors_died = " << this->actors_died << endl;
 }
Actor * Worker::find_actor (int actor_id) private
finds the requested actor
Parameters
id of the actor to find
Returns
Returns pointer to the requested actor
References actors.
{
     for (auto actor : this->actors)
         if(actor->get_id() == actor_id)
             return actor;
     return nullptr;
 }
void Worker::kill_all_actors () private
kill all the actors in the worker
References ACTOR_ID, actors, COMMAND, KILL_ACTOR_COMMAND, MASTER_PID, Messenger::send_message(), and Message::set().
{
     for (auto actor : this->actors) {
         Message message;
         message.set(COMMAND, KILL_ACTOR_COMMAND);
         message.set(ACTOR_ID, actor->get_id());
         Messenger::send_message(MASTER_PID, message);
     }
 }
int Worker::process (Message message) private
Executes the parse message function of the worker.
Parameters
message The input message for worker
References ACTOR_ID, ACTOR_ID_DEST, actors, add_actor(), COMMAND, find_actor(), Message::get(), KILL_ACTOR_COMMAND, KILL_WORKER_COMMAND, MASTER_PID, pid, Actor::process(), remove_actor(), Messenger::send_message(), spawn_actor, SPAWN_ACTOR_COMMAND, start_simulation, and START_WORKER_COMMAND.
{
     switch((int) message.get(COMMAND)) {
         case START_WORKER_COMMAND:
             this->start_simulation = true;
             cout << "Worker " << this->pid << " started: actors_num = " << this->actors.size() << endl;
             break;
         case KILL_WORKER_COMMAND:
             Messenger::send_message(MASTER_PID, message);
             return 1;
         case SPAWN_ACTOR_COMMAND:
             this->add_actor(Worker::spawn_actor(message));
             break;
         case KILL_ACTOR_COMMAND:
             this->remove_actor(message.get(ACTOR_ID));
             break;
         default:
             Actor *actor = this->find_actor(message.get(ACTOR_ID_DEST));
             if(actor)
                 actor->process(message);
     }
     return 0;
 }
void Worker::register_spawn_actor (Actor * spawn_actor)(Message message) static
registers the spawn actor function
Parameters
function pointer to the given callback that spawns actors
References spawn_actor.
{
     Worker::spawn_actor = spawn_actor;
 }
void Worker::remove_actor (int actor_id) private
removes the requested actor
Parameters
id of the actor to kill
References actors, and actors_died.
{
     this->actors_died++;
     for (unsigned int i = 0; i < this->actors.size(); ++i) {
         if(this->actors[i]->get_id() == actor_id) {
             delete this->actors[i];
             this->actors[i] = nullptr;
             this->actors.erase(this->actors.begin() + i);
             return;
         }
     }
     assert(0);
 }
void Worker::run ()
main functionality of worker
References compute(), process(), and Messenger::receive_message().
                  {
     int outstanding, source_pid;
     MPI_Status status;
     do {
         MPI_Iprobe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &outstanding, &status);
         if(!outstanding) {
             this->compute();
         }
         else {
             source_pid=status.MPI_SOURCE;
             Message message = Messenger::receive_message(source_pid);
             if(this->process(message)) break;
         }
     } while(1);
 }
Member Data Documentation
vector<Actor*> Worker::actors private
vector that contains pointers to the actors that live in this worker
int Worker::actors_died private
number of died actors in this worker
int Worker::actors_spawned private
number of spawned actors in this worker
int Worker::pid private
worker process number
Actor *(* Worker::spawn_actor)(Message message) static private
function pointer to the given callback that spawns actors
bool Worker::start_simulation private
indicates if the simulation should start or not
The documentation for this class was generated from the following files:
actor_framework/worker.h
actor_framework/worker.cpp