Actor framework: Master Class Reference
Master Class Reference
#include <master.h>
Static Public Member Functions
static void set_workers_num (int workers_num)
Sets the number of active worker processes.
static void spawn_actor (Message message)
Send message to a worker to spawn a new actor.
static void run ()
Runs the main master code waiting for messages.
static void finalize ()
Finalises the master process by sending finalisation messages to the workers.
Static Private Member Functions
static int get_next_worker ()
Find the worker pid that the next actor will belong.
static void start_simulation ()
Notifies the workers to start and starts the simulation.
static int parse_message (int source_pid, Message message)
Parses the given message and does the appropriate functionality.
Static Private Attributes
static int workers_num = 0
number of active worker processes
static int next_actor_id = 0
unique id for the next actor to be spawned
static int actors_died = 0
number of actors died during the simulation
Detailed Description
class containing information and functionality for the Master process
Member Function Documentation
void Master::finalize () static
Finalises the master process by sending finalisation messages to the workers.
References actors_died, COMMAND, Message::get(), KILL_WORKER_COMMAND, next_actor_id, Messenger::receive_message(), Messenger::send_message(), Message::set(), and workers_num.
                       {
     for (int worker_pid = 1; worker_pid <= Master::workers_num; ++worker_pid) {
         Message message;
         message.set(COMMAND, KILL_WORKER_COMMAND);
         Messenger::send_message(worker_pid, message);
     }
     for (int worker_pid = 1; worker_pid <= Master::workers_num; ++worker_pid) {
         Message message;
         do {
             //discard messages and breaks when a KILL_WORKER_COMMAND is received
             message = Messenger::receive_message(worker_pid);
         } while (message.get(COMMAND) != KILL_WORKER_COMMAND);
     }
     cout << "Master finalized: actors_spawned = " << Master::next_actor_id << ", actors_died = " << Master::actors_died << endl;
 }
int Master::get_next_worker () static private
Find the worker pid that the next actor will belong.
Returns
Returns the worker pid
References next_actor_id, and workers_num.
{
     return Master::next_actor_id%workers_num + 1;
 }
int Master::parse_message (int source_pid, Message message) static private
Parses the given message and does the appropriate functionality.
Parameters
source_pid Pid of the source process
message Input message for processing
Returns
Returns 1 of the simulation should exit otherwise it returns 0
References actors_died, COMMAND, Message::get(), KILL_ACTOR_COMMAND, KILL_ALL_ACTORS_COMMAND, spawn_actor(), and SPAWN_ACTOR_COMMAND.
{
     switch((int)message.get(COMMAND)) {
         case KILL_ALL_ACTORS_COMMAND:
             return 1;
         case SPAWN_ACTOR_COMMAND:
             Master::spawn_actor(message);
             break;
         case KILL_ACTOR_COMMAND:
             Master::actors_died++;
             break;
         default:
             assert(0);
     }
     return 0;
 }
void Master::run () static
Runs the main master code waiting for messages.
References parse_message(), Messenger::receive_message(), and start_simulation().
                  {
     int outstanding, source_pid;
     MPI_Status status;
     Master::start_simulation();
     do {
         MPI_Iprobe(MPI_ANY_SOURCE, 0, MPI_COMM_WORLD, &outstanding, &status);
         if(outstanding) {
             source_pid=status.MPI_SOURCE;
             Message message = Messenger::receive_message(source_pid);
             if(Master::parse_message(source_pid, message)) break;
         }
     } while(1);
 }
void Master::set_workers_num (int workers_num) static
Sets the number of active worker processes.
Parameters
workers_num number of active worker processes
References workers_num.
{
     Master::workers_num = workers_num;
 }
void Master::spawn_actor (Message message) static
Send message to a worker to spawn a new actor.
Parameters
message Message for the creation of the new actor
References ACTOR_ID, COMMAND, get_next_worker(), next_actor_id, Messenger::send_message(), Message::set(), SPAWN_ACTOR_COMMAND, WORKER_PID, workers_num, and WORKERS_NUM.
{
     int worker_pid = Master::get_next_worker();
     message.set(COMMAND, SPAWN_ACTOR_COMMAND);
     message.set(ACTOR_ID, Master::next_actor_id);
     message.set(WORKER_PID, worker_pid);
     message.set(WORKERS_NUM, Master::workers_num);
     Messenger::send_message(worker_pid, message);
     Master::next_actor_id++;
 }
void Master::start_simulation () static private
Notifies the workers to start and starts the simulation.
References COMMAND, Messenger::send_message(), Message::set(), START_WORKER_COMMAND, and workers_num.
{
     Message message;
     message.set(COMMAND, START_WORKER_COMMAND);
     for (int worker_pid = 1; worker_pid <= Master::workers_num; ++worker_pid)
         Messenger::send_message(worker_pid, message);
     cout << "Master start_simulation\n";
 }
Member Data Documentation
int Master::actors_died = 0 static private
number of actors died during the simulation
int Master::next_actor_id = 0 static private
unique id for the next actor to be spawned
int Master::workers_num = 0 static private
number of active worker processes
The documentation for this class was generated from the following files:
actor_framework/master.h
actor_framework/master.cpp