Actor framework: simulation/clock.cpp File Reference
clock.cpp File Reference
#include "clock.h"
Functions
static void compute_in_month (Actor *actor)
in month computation when clock is waiting for month to complete
static void compute_end_of_month (Actor *actor)
in the end of month computation where clock waits cells to respond
static void parse_message_in_month (Actor *actor, Message message)
parses messages for squirrels updates
static void parse_message_end_of_month (Actor *actor, Message message)
parses messages for squirrels and cell updates
Function Documentation
static void compute_end_of_month (Actor * actor) static
in the end of month computation where clock waits cells to respond
Parameters
actor Pointer to this Actor
References Clock::alive_squirrels, Clock::begin_time, CELL_NUM, Clock::cells_ready, FINISH, IN_MONTH, Clock::infected_squirrels, Actor::kill_all(), Clock::max_months, Clock::month, Actor::set_state(), Clock::write_output_files(), and Clock::write_output_stream().
{
     Clock *clock = dynamic_cast<Clock*>(actor);
     if(clock->cells_ready == CELL_NUM) {
         clock->write_output_stream();
         cout << "Month " << clock->month << ": alive_squirrels = " << clock->alive_squirrels << ", infected_squirrels = " << clock->infected_squirrels << endl;
         if(clock->month >= clock->max_months || clock->alive_squirrels == 0 || clock->alive_squirrels > 200) {
             if(clock->alive_squirrels == 0)
                 cout << "Simulation termination: all squirrels died\n";
             if(clock->alive_squirrels > 200)
                 cout << "Simulation termination: squirrels exceeded 200\n";
             clock->set_state(FINISH);
             clock->write_output_files();
             clock->kill_all();
         }
         else {
             clock->cells_ready = 0;
             clock->month++;
             clock->begin_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
             clock->set_state(IN_MONTH);
         }
     }
 }
static void compute_in_month (Actor * actor) static
in month computation when clock is waiting for month to complete
Parameters
actor Pointer to this Actor
References Clock::begin_time, CELL_NUM, COMMAND, END_OF_MONTH, Actor::send_msg(), Message::set(), Actor::set_state(), TIMESTEP_DURATION, and TIMESTEP_END.
{
     Clock *clock = dynamic_cast<Clock*>(actor);
     milliseconds curr_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
     if((curr_time - clock->begin_time).count() > TIMESTEP_DURATION) {
         clock->begin_time = curr_time;
         clock->set_state(END_OF_MONTH);
         Message message;
         message.set(COMMAND, TIMESTEP_END);
         for (int cell_id = 0; cell_id < CELL_NUM; ++cell_id) {
             clock->send_msg(cell_id, message);
         }
     }
 }
static void parse_message_end_of_month (Actor * actor, Message message) static
parses messages for squirrels and cell updates
Parameters
actor Pointer to this Actor
message Input message
References Clock::alive_squirrels, Clock::cells_ready, COMMAND, Message::get(), INFECTED_SQUIRREL_COMMAND, Clock::infected_squirrels, INFECTION_LEVEL, Clock::infection_level, KILL_SQUIRREL_COMMAND, POPULATION_INFLUX, Clock::population_influx, SPAWN_SQUIRREL_COMMAND, and TIMESTEP_END.
{
     Clock *clock = dynamic_cast<Clock*>(actor);
     if(message.get(COMMAND) == TIMESTEP_END) {
         clock->population_influx[clock->cells_ready] = message.get(POPULATION_INFLUX);
         clock->infection_level[clock->cells_ready] = message.get(INFECTION_LEVEL);
         clock->cells_ready++;
     }
     else if(message.get(COMMAND) == SPAWN_SQUIRREL_COMMAND) {
         clock->alive_squirrels++;
     }
     else if(message.get(COMMAND) == KILL_SQUIRREL_COMMAND) {
         clock->alive_squirrels--;
         clock->infected_squirrels--;
     }
     else if(message.get(COMMAND) == INFECTED_SQUIRREL_COMMAND) {
         clock->infected_squirrels++;
     }
     else
         assert(0);
 }
static void parse_message_in_month (Actor * actor, Message message) static
parses messages for squirrels updates
Parameters
actor Pointer to this Actor
message Input message
References Clock::alive_squirrels, COMMAND, Message::get(), INFECTED_SQUIRREL_COMMAND, Clock::infected_squirrels, KILL_SQUIRREL_COMMAND, and SPAWN_SQUIRREL_COMMAND.
{
     Clock *clock = dynamic_cast<Clock*>(actor);
     if(message.get(COMMAND) == SPAWN_SQUIRREL_COMMAND) {
         clock->alive_squirrels++;
     }
     else if(message.get(COMMAND) == KILL_SQUIRREL_COMMAND) {
         clock->alive_squirrels--;
         clock->infected_squirrels--;
     }
     else if(message.get(COMMAND) == INFECTED_SQUIRREL_COMMAND) {
         clock->infected_squirrels++;
     }
     else
         assert(0);
 }