Actor framework: Clock Class Reference
Clock Class Reference
Derived class of Actor.
#include <clock.h>
Public Member Functions
void write_output_stream ()
updates the output stringstream
void write_output_files ()
writes the output files with the content of the stringstreams
Clock (int id, int workers_num, int max_months, int init_squirrels_no, int init_inf_squirrels_no)
Clock constructor.
~Clock ()
Clock destructor.
Public Member Functions inherited from Actor
Actor (int id, int type, int workers_num)
Actor constructor.
virtual ~Actor ()=0
Actor destructor.
int get_id ()
void set_state (int state)
Sets new FSM state to the Actor.
void compute ()
Executes the compute function of the Actor based on its current state.
void process (Message message)
Executes the parse message function of the Actor based on its current state.
void send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
void kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
Public Attributes
vector< int > population_influx
Vector containing the population influx of the cells for the current month.
vector< int > infection_level
Vector containing the infection level of the cells for the current month.
milliseconds begin_time
Time in milliseconds that the month began.
int max_months
Maximum number of simulation months.
int month
Current month.
int cells_ready
number of cells responded for end of month report
int alive_squirrels
number of alive squirrels
int infected_squirrels
number of infected squirrels
Static Public Attributes
static stringstream population_influx_stream
stringstream for the population_influx output file
static stringstream infection_level_stream
stringstream for the infection_level_stream output file
static stringstream alive_squirrels_stream
static stringstream infected_squirrels_stream
Additional Inherited Members
Protected Member Functions inherited from Actor
void register_state (int state, void(compute_f)(Actor *))
Adds the given compute function to the compute_map based on the given state in FSM.
void register_state (int state, void(parse_message_f)(Actor *, Message))
Adds the given parse message function to the compute_map based on the given state in FSM.
void create_actor (Message message)
Sends message to the master to create a new Actor.
void kill_actor ()
Sends message to the master and the appropriate worker(this worker) to kill this actor.
Detailed Description
Derived class of Actor.
class Clock is an Actor holding vital information for this entity and providing functionality
Constructor & Destructor Documentation
Clock::Clock (int id, int workers_num, int max_months, int init_squirrels_no, int init_inf_squirrels_no)
Clock constructor.
Parameters
id id of the clock
workers_num number of active workers it should be passed in the parent class
max_months Number of months to simulate
init_squirrels_no Number of initially alive squirrels
init_inf_squirrels_no Number of initially infected squirrels
References alive_squirrels, begin_time, CELL_NUM, cells_ready, compute_end_of_month(), compute_in_month(), END_OF_MONTH, IN_MONTH, infected_squirrels, infection_level, max_months, month, parse_message_end_of_month(), parse_message_in_month(), population_influx, Actor::register_state(), and Actor::set_state().
                                                                                                      : Actor(id, ACTOR_TYPE_CLOCK, workers_num) {
     this->max_months = max_months;
     this->month = 1;
     this->cells_ready = 0;
     this->alive_squirrels = init_squirrels_no;
     this->infected_squirrels = init_inf_squirrels_no;
     this->population_influx = vector<int>(CELL_NUM);
     this->infection_level = vector<int>(CELL_NUM);
     this->begin_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
     for (int i = 0; i < CELL_NUM; ++i) {
         this->population_influx[i] = 0;
         this->infection_level[i] = 0;
     }
     this->set_state(IN_MONTH);
     this->register_state(IN_MONTH, compute_in_month);
     this->register_state(END_OF_MONTH, compute_end_of_month);
     this->register_state(IN_MONTH, parse_message_in_month);
     this->register_state(END_OF_MONTH, parse_message_end_of_month);
 }
Clock::~Clock ()
Clock destructor.
 {}
Member Function Documentation
void Clock::write_output_files ()
writes the output files with the content of the stringstreams
References alive_squirrels_stream, infected_squirrels_stream, infection_level_stream, and population_influx_stream.
{
     ofstream population_influx_file, infection_level_file, alive_squirrels_file, infected_squirrels_file;
     population_influx_file.open ("./data/population_influx.tsv");
     infection_level_file.open ("./data/infection_level.tsv");
     alive_squirrels_file.open ("./data/alive_squirrels.tsv");
     infected_squirrels_file.open ("./data/infected_squirrels.tsv");
     population_influx_file << Clock::population_influx_stream.rdbuf();
     infection_level_file << Clock::infection_level_stream.rdbuf();
     alive_squirrels_file << Clock::alive_squirrels_stream.rdbuf();
     infected_squirrels_file << Clock::infected_squirrels_stream.rdbuf();
     population_influx_file.close();
     infection_level_file.close();
     alive_squirrels_file.close();
     infected_squirrels_file.close();
 }
void Clock::write_output_stream ()
updates the output stringstream
References alive_squirrels, alive_squirrels_stream, CELL_NUM, infected_squirrels, infected_squirrels_stream, infection_level, infection_level_stream, month, population_influx, and population_influx_stream.
{
     if(this->month == 1) {
         Clock::population_influx_stream << "month";
         Clock::infection_level_stream << "month";
         Clock::alive_squirrels_stream << "month";
         Clock::infected_squirrels_stream << "month";
         for (int i = 0; i < CELL_NUM; ++i) {
             Clock::population_influx_stream << "\tCell " << i;
             Clock::infection_level_stream << "\tCell " << i;
         }
         Clock::population_influx_stream << "\n";
         Clock::infection_level_stream << "\n";
         Clock::alive_squirrels_stream << "\tSquirrels Number\n";
         Clock::infected_squirrels_stream << "\tSquirrels Number\n";
     }
     Clock::population_influx_stream << this->month;
     Clock::infection_level_stream << this->month;
     for(auto population_influx: this->population_influx) {
         this->population_influx_stream << "\t" << population_influx;
     }
     for(auto infection_level: this->infection_level) {
         Clock::infection_level_stream << "\t" << infection_level;
     }
     Clock::population_influx_stream << endl;
     Clock::infection_level_stream << endl;
     Clock::alive_squirrels_stream << this->month << "\t" << this->alive_squirrels << endl;
     Clock::infected_squirrels_stream << this->month << "\t" << this->infected_squirrels << endl;
 }
Member Data Documentation
int Clock::alive_squirrels
number of alive squirrels
stringstream Clock::alive_squirrels_stream static
milliseconds Clock::begin_time
Time in milliseconds that the month began.
int Clock::cells_ready
number of cells responded for end of month report
int Clock::infected_squirrels
number of infected squirrels
stringstream Clock::infected_squirrels_stream static
vector<int> Clock::infection_level
Vector containing the infection level of the cells for the current month.
stringstream Clock::infection_level_stream static
stringstream for the infection_level_stream output file
int Clock::max_months
Maximum number of simulation months.
int Clock::month
Current month.
vector<int> Clock::population_influx
Vector containing the population influx of the cells for the current month.
stringstream Clock::population_influx_stream static
stringstream for the population_influx output file
The documentation for this class was generated from the following files:
simulation/clock.h
simulation/clock.cpp