Actor framework: Cell Class Reference
Cell Class Reference
Derived class of Actor.
#include <cell.h>
Public Member Functions
Cell (int id, int workers_num)
Cell constructor.
~Cell ()
Cell destructor.
void visited (Message message)
This function is called when the cell is visited by a squirrel.
Public Member Functions inherited from Actor
Actor (int id, int type, int workers_num)
Actor constructor.
virtual ~Actor ()=0
Actor destructor.
int get_id ()
void set_state (int state)
Sets new FSM state to the Actor.
void compute ()
Executes the compute function of the Actor based on its current state.
void process (Message message)
Executes the parse message function of the Actor based on its current state.
void send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
void kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
Public Attributes
int month
current month in the cell
vector< int > population_influx
populationInflux is a vector containing the total number of squirrels that have stepped into the specific cell at some point during the past 3 months
vector< int > infection_level
infection_level is a vector containing the total number of infected squirrels that have stepped into the specific cell at some point during the past 2 months
Additional Inherited Members
Protected Member Functions inherited from Actor
void register_state (int state, void(compute_f)(Actor *))
Adds the given compute function to the compute_map based on the given state in FSM.
void register_state (int state, void(parse_message_f)(Actor *, Message))
Adds the given parse message function to the compute_map based on the given state in FSM.
void create_actor (Message message)
Sends message to the master to create a new Actor.
void kill_actor ()
Sends message to the master and the appropriate worker(this worker) to kill this actor.
Detailed Description
Derived class of Actor.
class Cell is an Actor holding vital information for this entity and providing functionality
Constructor & Destructor Documentation
Cell::Cell (int id, int workers_num)
Cell constructor.
Parameters
id id of the cell
workers_num number of active workers it should be passed in the parent class
References infection_level, month, parse_message_simulate(), population_influx, Actor::register_state(), Actor::set_state(), and SIMULATE.
                                  : Actor(id, ACTOR_TYPE_CELL, workers_num) {
     this->month = 1;
     this->population_influx = vector<int>(3);
     this->infection_level = vector<int>(2);
     for (int i = 0; i <3; ++i)
         this->population_influx[i] = 0;
     for (int i = 0; i <2; ++i)
         this->infection_level[i] = 0;
     this->set_state(SIMULATE);
     this->register_state(SIMULATE, parse_message_simulate);
 }
Cell::~Cell ()
Cell destructor.
 {}
Member Function Documentation
void Cell::visited (Message message)
This function is called when the cell is visited by a squirrel.
Parameters
message input message containing health status from the squirrel
References Message::get(), HEALTHY, infection_level, month, and population_influx.
{
     this->population_influx[this->month%3]++;
     if(message.get(HEALTHY) == 0)
         this->infection_level[this->month%2]++;
 }
Member Data Documentation
vector<int> Cell::infection_level
infection_level is a vector containing the total number of infected squirrels that have stepped into the specific cell at some point during the past 2 months
int Cell::month
current month in the cell
vector<int> Cell::population_influx
populationInflux is a vector containing the total number of squirrels that have stepped into the specific cell at some point during the past 3 months
The documentation for this class was generated from the following files:
simulation/cell.h
simulation/cell.cpp