Actor framework: Actor Class Reference
Actor Class Reference abstract
Base abstract class of Actors.
#include <actor.h>
Public Member Functions
Actor (int id, int type, int workers_num)
Actor constructor.
virtual ~Actor ()=0
Actor destructor.
int get_id ()
void set_state (int state)
Sets new FSM state to the Actor.
void compute ()
Executes the compute function of the Actor based on its current state.
void process (Message message)
Executes the parse message function of the Actor based on its current state.
void send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
void kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
Protected Member Functions
void register_state (int state, void(compute_f)(Actor *))
Adds the given compute function to the compute_map based on the given state in FSM.
void register_state (int state, void(parse_message_f)(Actor *, Message))
Adds the given parse message function to the compute_map based on the given state in FSM.
void create_actor (Message message)
Sends message to the master to create a new Actor.
void kill_actor ()
Sends message to the master and the appropriate worker(this worker) to kill this actor.
Private Member Functions
int get_worker (int actor_id)
Find the worker pid that the given actor id belongs.
Private Attributes
int id
unique identification of actor
int workers_num
number of active worker processes
int state
current state of Actor in FSM
int type
type of Actor it is described in the simulation during the construction of the derived object
map< int, void(*)(Actor *)> compute_map
map data structure that contains a compute Actor function for a given state in FSM
map< int, void(*)(Actor
*, Message)> parse_message_map
map data structure that contains a parse message Actor function for a given state in FSM
Detailed Description
Base abstract class of Actors.
A class that is inhereted by Actors in the user simulation poviding a mechanism to communicate with other actors and operate
Constructor & Destructor Documentation
Actor::Actor (int id, int type, int workers_num)
Actor constructor.
Parameters
id Actor id
type Actor type
workers_num number of active worker processes
References id, state, type, and workers_num.
{
     assert(id >= 0 && workers_num >=1);
     this->id = id;
     this->type = type;
     this->workers_num = workers_num;
     this->state = 0;
 }
Actor::~Actor () pure virtual
Actor destructor.
 {}
Member Function Documentation
void Actor::compute ()
Executes the compute function of the Actor based on its current state.
References compute_map, and state.
                     {
     if(this->compute_map[this->state])
         this->compute_map[this->state](this);
 }
void Actor::create_actor (Message message) protected
Sends message to the master to create a new Actor.
Parameters
message The input message containing information about the new Actor
References ACTOR_TYPE, COMMAND, MASTER_PID, Messenger::send_message(), Message::set(), SPAWN_ACTOR_COMMAND, and type.
{
     message.set(COMMAND, SPAWN_ACTOR_COMMAND);
     message.set(ACTOR_TYPE, this->type);
     Messenger::send_message(MASTER_PID, message);
 }
int Actor::get_id ()
Returns
Returns the Actor id
References id.
                   {
     return this->id;
 }
int Actor::get_worker (int actor_id) private
Find the worker pid that the given actor id belongs.
Parameters
actor_id Actor id
Returns
Returns the worker pid
References workers_num.
{
     return actor_id%this->workers_num + 1;
 }
void Actor::kill_actor () protected
Sends message to the master and the appropriate worker(this worker) to kill this actor.
References ACTOR_ID, COMMAND, get_id(), get_worker(), KILL_ACTOR_COMMAND, MASTER_PID, Messenger::send_message(), and Message::set().
{
     int actor_id = this->get_id();
     Message message;
     message.set(COMMAND, KILL_ACTOR_COMMAND);
     message.set(ACTOR_ID, actor_id);
     Messenger::send_message(this->get_worker(actor_id), message);
     Messenger::send_message(MASTER_PID, message);
 }
void Actor::kill_all ()
Sends message to the master to kill all actors, after this call the simulation is finilised.
References COMMAND, KILL_ALL_ACTORS_COMMAND, MASTER_PID, Messenger::send_message(), and Message::set().
                      {
     Message message;
     message.set(COMMAND, KILL_ALL_ACTORS_COMMAND);
     Messenger::send_message(MASTER_PID, message);
 }
void Actor::process (Message message)
Executes the parse message function of the Actor based on its current state.
Parameters
message The input message for Actor
References parse_message_map, and state.
{
     if(this->parse_message_map[this->state])
         this->parse_message_map[this->state](this, message);
 }
void Actor::register_state (int state, void(compute_f)(Actor *)) protected
Adds the given compute function to the compute_map based on the given state in FSM.
Parameters
state FSM state
compute_f static compute function pointer
References compute_map, and state.
{
     this->compute_map[state] = compute_f;
 }
void Actor::register_state (int state, void(parse_message_f)(Actor *, Message)) protected
Adds the given parse message function to the compute_map based on the given state in FSM.
Parameters
state FSM state
compute_f static parse message function pointer
References parse_message_map, and state.
{
     this->parse_message_map[state] = parse_message_f;
 }
void Actor::send_msg (int actor_id, Message message)
Send the given message to the specified actor_id.
Parameters
actor_id The receiver actor id
message The message to send
References ACTOR_ID, ACTOR_ID_DEST, COMMAND, Message::get(), get_id(), get_worker(), Messenger::send_message(), and Message::set().
{
     if(message.get(COMMAND) <= 4) {
         cerr << "Invalid message error: COMMAND code should be greater that 4\n";
         exit(1);
     }
     message.set(ACTOR_ID, this->get_id());
     message.set(ACTOR_ID_DEST, actor_id);
     Messenger::send_message(this->get_worker(actor_id), message);
 }
void Actor::set_state (int state)
Sets new FSM state to the Actor.
Parameters
state FSM state
References state.
{
     this->state = state;
 }
Member Data Documentation
map<int, void (*)(Actor*)> Actor::compute_map private
map data structure that contains a compute Actor function for a given state in FSM
int Actor::id private
unique identification of actor
map<int, void (*)(Actor*, Message)> Actor::parse_message_map private
map data structure that contains a parse message Actor function for a given state in FSM
int Actor::state private
current state of Actor in FSM
int Actor::type private
type of Actor it is described in the simulation during the construction of the derived object
int Actor::workers_num private
number of active worker processes
The documentation for this class was generated from the following files:
actor_framework/actor.h
actor_framework/actor.cpp