Actor framework: simulation/squirrel.cpp File Reference
squirrel.cpp File Reference
#include "squirrel.h"
Functions
static void compute_live (Actor *actor)
main computation cycle when squirrel is alive
static void parse_message_interact (Actor *actor, Message message)
parses the response of the visited cell and updates its values
Function Documentation
static void compute_live (Actor * actor) static
main computation cycle when squirrel is alive
Parameters
actor Pointer to this Actor
References Squirrel::begin_time, Squirrel::birth(), Squirrel::die(), Squirrel::move(), NEXT_STEP_DELAY, and Squirrel::should_act().
{
     Squirrel *squirrel = dynamic_cast<Squirrel*>(actor);
     milliseconds curr_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
     if((curr_time - squirrel->begin_time).count() > NEXT_STEP_DELAY) {
         if(squirrel->should_act()) {
             squirrel->birth();
             squirrel->die();
             squirrel->move();
         }
     }
 }
static void parse_message_interact (Actor * actor, Message message) static
parses the response of the visited cell and updates its values
Parameters
actor Pointer to this Actor
message Input message
References Squirrel::begin_time, COMMAND, Message::get(), Squirrel::healthy, Squirrel::infected_steps, INFECTION_LEVEL, Squirrel::infection_level, LIVE, POPULATION_INFLUX, Squirrel::population_influx, Actor::set_state(), Squirrel::step_no, STEPS_MEMORY, and VISIT_CELL_COMMAND.
{
     Squirrel *squirrel = dynamic_cast<Squirrel*>(actor);
     if(message.get(COMMAND) == VISIT_CELL_COMMAND) {
         // cout << "Squirrel parse_message_interact: " << squirrel->get_id() << "\n";
         squirrel->set_state(LIVE);
         squirrel->population_influx[squirrel->step_no%STEPS_MEMORY] = message.get(POPULATION_INFLUX);
         squirrel->infection_level[squirrel->step_no%STEPS_MEMORY] = message.get(INFECTION_LEVEL);
         squirrel->step_no++;
         squirrel->begin_time = duration_cast< milliseconds >(system_clock::now().time_since_epoch());
         if(squirrel->healthy == 0)
             squirrel->infected_steps++;
     }
     else
         assert(0);
 }